(()=>{'use strict';
const c=document.getElementById('gameCanvas'),x=c.getContext('2d'),$=id=>document.getElementById(id),U={start:$('startOverlay'),pause:$('pauseOverlay'),result:$('resultOverlay'),startBtn:$('startBtn'),restartBtn:$('restartBtn'),fxBtn:$('effectToggle'),time:$('timeText'),phase:$('phaseText'),boss:$('bossBar'),hearts:$('hearts'),score:$('scoreText'),combo:$('comboText'),dash:$('dashText'),shield:$('shieldText'),state:$('stateText'),wins:$('winsText'),bestScore:$('bestScoreText'),bestTime:$('bestTimeText'),rk:$('resultKicker'),rt:$('resultTitle'),rs:$('resultSummary'),grade:$('gradeText'),rscore:$('scoreResult'),rdodge:$('dodgeResult')};
const ROUND=28,INT=750,KEY='raidzero:v1',PR=12,SPEED=220,DASH=105,DASH_CD=3,DASH_I=.5,SHIELD_I=1.5,HIT_I=.82,S_DODGE=50,S_SCORE=3600;
let raf=0,last=0,acc=0,reduced=false,blurPause=false,rec=load();const inp={up:0,down:0,left:0,right:0},dbg={coreInputEvents:0,coreActions:0,lastResetSignature:'',errors:[]};let s=fresh();
function shieldPlan(){let q=[rnd(5.5,7.5)];if(Math.random()<.65)q.push(rnd(15,18));return q}
function fresh(){return{mode:'ready',elapsed:0,timeLeft:ROUND,phase:1,hp:5,score:0,combo:0,dodges:0,dashCooldown:0,invuln:0,shieldTime:0,player:{x:480,y:385},hazards:[],powerups:[],shieldSpawnQueue:shieldPlan(),particles:[],screenShake:0,dashFx:null,clearFx:null,lastPatternName:'-',roundStartedAt:0,result:null}}
function safe(r){if(!r||typeof r!=='object')return{wins:0,bestScore:0,bestTime:0};let w=+r.wins,b=+r.bestScore,t=+r.bestTime;return{wins:Number.isFinite(w)&&w>=0?Math.floor(w):0,bestScore:Number.isFinite(b)&&b>=0?Math.floor(b):0,bestTime:Number.isFinite(t)&&t>=0&&t<=ROUND?t:0}}
function load(){try{let v=localStorage.getItem(KEY);return v?safe(JSON.parse(v)):{wins:0,bestScore:0,bestTime:0}}catch{return{wins:0,bestScore:0,bestTime:0}}}function save(){try{localStorage.setItem(KEY,JSON.stringify(rec))}catch{}}
function reset(){s=fresh();Object.keys(inp).forEach(k=>inp[k]=0);acc=0;last=performance.now();blurPause=false;dbg.lastResetSignature=`${s.mode}|${s.timeLeft}|${s.hp}|${s.score}|${s.combo}|${s.hazards.length}`;ui()}
function start(){reset();s.mode='playing';s.roundStartedAt=performance.now();U.start.classList.remove('show');U.result.classList.remove('show');U.pause.classList.remove('show');U.result.setAttribute('aria-hidden','true');U.pause.setAttribute('aria-hidden','true');banner('PHASE 1');pattern(1);ui()}
function pause(force){if(!['playing','paused'].includes(s.mode))return;let p=typeof force==='boolean'?force:s.mode==='playing';s.mode=p?'paused':'playing';U.pause.classList.toggle('show',p);U.pause.setAttribute('aria-hidden',p?'false':'true');if(!p)last=performance.now();ui()}
function end(ok){if(s.mode!=='playing')return;s.mode=ok?'success':'fail';let survived=Math.min(ROUND,s.elapsed);s.powerups.length=0;if(ok){s.hazards.length=0;s.dashFx=null;if(!reduced){s.clearFx={startedAt:performance.now(),duration:1};burst(480,68,64,'#75eaff');burst(480,270,42,'#a7f5ff')}}else if(!reduced)burst(480,270,28,'#ff5369');let g=grade(ok);s.result={success:ok,grade:g,score:Math.floor(s.score),dodges:s.dodges,survived};if(ok)rec.wins++;rec.bestScore=Math.max(rec.bestScore,Math.floor(s.score));rec.bestTime=Math.max(rec.bestTime,survived);save();U.rk.textContent=ok?'RAID CLEAR':'TRAINING FAILED';U.rt.textContent=ok?'NULL CORE 생존 성공':'레이드 실패';U.rs.textContent=ok?`3개 페이즈를 모두 버텼습니다. S 조건: 무피격 + 회피 ${S_DODGE}+ + ${S_SCORE.toLocaleString()}점+`:`${survived.toFixed(1)}초 생존 후 HP가 0이 되었습니다.`;U.grade.textContent=g;U.rscore.textContent=Math.floor(s.score).toLocaleString();U.rdodge.textContent=s.dodges;U.result.classList.add('show');U.result.setAttribute('aria-hidden','false');ui()}
function grade(ok){if(!ok)return s.elapsed>=20?'C':'D';if(s.hp===5&&s.dodges>=S_DODGE&&s.score>=S_SCORE)return'S';if(s.hp>=4)return'A';if(s.hp>=2)return'B';return'C'}
function vec(){let a=(inp.right?1:0)-(inp.left?1:0),b=(inp.down?1:0)-(inp.up?1:0);if(!a&&!b)return{x:0,y:0};let l=Math.hypot(a,b);return{x:a/l,y:b/l}}
function dash(){dbg.coreInputEvents++;if(s.mode!=='playing')return;dbg.coreActions++;if(s.dashCooldown>0){s.lastPatternName='DASH BLOCKED';return}let v=vec(),dx=v.x,dy=v.y;if(!dx&&!dy)dy=-1;let fx=s.player.x,fy=s.player.y,tx=cl(fx+dx*DASH,22,938),ty=cl(fy+dy*DASH,18,468);s.player.x=tx;s.player.y=ty;s.dashCooldown=DASH_CD;s.invuln=Math.max(s.invuln,DASH_I);s.score+=18;if(!reduced){s.dashFx={fromX:fx,fromY:fy,toX:tx,toY:ty,age:0,duration:.28};burst(fx,fy,10,'#57e7ff');burst(tx,ty,20,'#c7fbff')}}
function add(type,o){s.hazards.push(Object.assign({type,t:0,hit:false},o))}function circle(a,b,r,w=.74){add('circle',{x:a,y:b,r,warning:w,active:.22})}function donut(a,b,i,o,w=.78){add('donut',{x:a,y:b,inner:i,outer:o,warning:w,active:.23})}function beam(a,w=60,z=.7){add('beam',{angle:a,width:w,warning:z,active:.2})}function cross(a,b,w=54,z=.7){add('cross',{x:a,y:b,width:w,warning:z,active:.21})}function aim(sc=1,w=.67){circle(s.player.x,s.player.y,64*sc,w)}function ring(n=5){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,d=95+Math.random()*130;circle(480+Math.cos(a)*d,270+Math.sin(a)*d,46+Math.random()*18,.68+Math.random()*.14)}}
function pattern(first=0){if(s.mode!=='playing')return;if(first){aim(.92,.72);s.lastPatternName='추적 장판';return}let p=s.phase,q=Math.random();if(p===1){q<.5?(aim(1,.64),s.lastPatternName='추적 원형 장판'):(ring(5),s.lastPatternName='5연속 원형 장판');return}if(p===2){if(q<.32){beam(Math.random()*Math.PI,66,.66);s.lastPatternName='회전 레이저'}else if(q<.64){donut(480,270,92,198,.72);s.lastPatternName='도넛 장판'}else{aim(1,.6);circle(cl(s.player.x+rnd(-95,95),70,890),cl(s.player.y+rnd(-95,95),70,445),54,.66);s.lastPatternName='2연속 추적 장판'}return}if(q<.25){beam(Math.random()*Math.PI,60,.5);beam(Math.random()*Math.PI,60,.7);circle(s.player.x,s.player.y,56,.62);s.lastPatternName='2연속 레이저 + 추적 장판'}else if(q<.5){cross(s.player.x,s.player.y,58,.54);circle(480,270,82,.72);circle(cl(s.player.x+rnd(-70,70),70,890),cl(s.player.y+rnd(-70,70),70,445),50,.64);s.lastPatternName='십자 + 중앙폭발 + 추적'}else if(q<.75){donut(s.player.x,s.player.y,50,120,.54);aim(.96,.58);beam(Math.random()*Math.PI,52,.72);s.lastPatternName='추적 도넛 + 원형 + 레이저'}else{ring(6);beam(Math.random()*Math.PI,56,.58);beam(Math.random()*Math.PI,48,.78);s.lastPatternName='6연속 장판 + 2연속 레이저'}}
function banner(t){s.lastPatternName=t;if(!reduced)burst(480,110,22,s.phase===3?'#ff7f66':'#57e7ff')}
function spawnShield(){let a=480,b=270;for(let i=0;i<12;i++){let nx=rnd(90,870),ny=rnd(130,420);a=nx;b=ny;if(Math.hypot(nx-s.player.x,ny-s.player.y)>=125)break}s.powerups.push({x:a,y:b,r:15,age:0,ttl:6});s.lastPatternName='SHIELD CORE 등장'}
function getShield(i){let it=s.powerups[i];if(!it)return;s.powerups.splice(i,1);s.shieldTime=SHIELD_I;s.invuln=Math.max(s.invuln,SHIELD_I);s.score+=75;s.lastPatternName='SHIELD CORE +1.5s';if(!reduced)burst(it.x,it.y,28,'#ffe06b')}
function update(dt){if(s.mode!=='playing')return;let old=s.phase;s.elapsed+=dt;s.timeLeft=Math.max(0,ROUND-s.elapsed);s.phase=s.elapsed<9?1:s.elapsed<18?2:3;if(s.phase!==old){banner(s.phase===3?'PHASE 3 — ENRAGE':`PHASE ${s.phase}`);acc=0}s.dashCooldown=Math.max(0,s.dashCooldown-dt);s.invuln=Math.max(0,s.invuln-dt);s.shieldTime=Math.max(0,s.shieldTime-dt);while(s.shieldSpawnQueue.length&&s.elapsed>=s.shieldSpawnQueue[0]){s.shieldSpawnQueue.shift();spawnShield()}if(s.dashFx&&(s.dashFx.age+=dt)>=s.dashFx.duration)s.dashFx=null;let v=vec();s.player.x=cl(s.player.x+v.x*SPEED*dt,22,938);s.player.y=cl(s.player.y+v.y*SPEED*dt,18,468);for(let i=s.powerups.length-1;i>=0;i--){let it=s.powerups[i];it.age+=dt;if(it.age>=it.ttl){s.powerups.splice(i,1);continue}if(Math.hypot(s.player.x-it.x,s.player.y-it.y)<=PR+it.r+5)getShield(i)}acc+=dt*1000;let ci=INT*(s.phase===3?.62:s.phase===2?.86:1.06);if(acc>=ci){acc=0;pattern()}for(let h of s.hazards){h.t+=dt;let active=h.t>=h.warning&&h.t<h.warning+h.active;if(active&&!h.hit&&s.invuln<=0&&hit(h)){h.hit=true;s.hp=Math.max(0,s.hp-1);s.combo=0;s.invuln=HIT_I;s.screenShake=reduced?0:10;if(!reduced)burst(s.player.x,s.player.y,20,'#ff5369');if(s.hp<=0){end(false);return}}if(!h.hit&&h.t>=h.warning+h.active){h.hit=true;s.dodges++;s.combo++;s.score+=25+Math.min(55,s.combo*2)}}s.hazards=s.hazards.filter(h=>h.t<h.warning+h.active+.25);for(let p of s.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=40*dt;p.life-=dt}s.particles=s.particles.filter(p=>p.life>0);s.screenShake=Math.max(0,s.screenShake-36*dt);s.score+=dt*(18+s.phase*4);if(s.elapsed>=ROUND){s.elapsed=ROUND;s.timeLeft=0;end(true)}ui()}
function hit(h){let px=s.player.x,py=s.player.y;if(h.type==='circle')return Math.hypot(px-h.x,py-h.y)<=h.r+PR;if(h.type==='donut'){let d=Math.hypot(px-h.x,py-h.y);return d>=h.inner-PR&&d<=h.outer+PR}if(h.type==='beam'){let dx=px-480,dy=py-270,per=Math.abs(-Math.sin(h.angle)*dx+Math.cos(h.angle)*dy);return per<=h.width/2+PR}if(h.type==='cross')return Math.abs(px-h.x)<=h.width/2+PR||Math.abs(py-h.y)<=h.width/2+PR;return false}
function burst(a,b,n,color){if(reduced)return;for(let i=0;i<n;i++){let z=Math.random()*Math.PI*2,v=rnd(55,190);s.particles.push({x:a,y:b,vx:Math.cos(z)*v,vy:Math.sin(z)*v,life:rnd(.22,.55),max:.55,color})}}
function render(){let sh=reduced?0:s.screenShake,sx=sh?rnd(-sh,sh):0,sy=sh?rnd(-sh,sh):0;x.save();x.clearRect(0,0,960,540);x.translate(sx,sy);arena();for(let h of s.hazards)drawH(h);drawItems();boss();dashFx();player();parts();clearFx();x.restore()}
function arena(){let g=x.createRadialGradient(480,180,50,480,240,560);g.addColorStop(0,'#101a28');g.addColorStop(1,'#05080d');x.fillStyle=g;x.fillRect(0,0,960,540);x.strokeStyle='rgba(87,231,255,.055)';x.lineWidth=1;for(let a=0;a<960;a+=48){x.beginPath();x.moveTo(a,0);x.lineTo(a,540);x.stroke()}for(let b=0;b<540;b+=48){x.beginPath();x.moveTo(0,b);x.lineTo(960,b);x.stroke()}x.fillStyle='rgba(18,30,45,.8)';x.fillRect(0,488,960,52);x.fillStyle='#7d90a9';x.font='12px monospace';x.fillText(`PATTERN: ${s.lastPatternName}`,18,519)}
function boss(){let a=480,b=46,col=s.phase===3?'#ff9a55':s.phase===2?'#ff6f8d':'#ff5369',alert=s.hazards.some(h=>h.t<h.warning);x.save();x.translate(a,b);x.globalAlpha=.9;x.shadowBlur=reduced?0:alert?14:5;x.shadowColor=col;x.fillStyle='#111823';x.beginPath();x.arc(0,0,11,0,Math.PI*2);x.fill();x.strokeStyle=col;x.lineWidth=2;x.beginPath();x.arc(0,0,16,0,Math.PI*2);x.stroke();x.fillStyle='#f7fbff';x.beginPath();x.arc(0,0,3.5,0,Math.PI*2);x.fill();x.restore()}
function drawItems(){for(let it of s.powerups){let p=reduced?1:1+Math.sin(performance.now()/170+it.x*.01)*.1;x.save();x.translate(it.x,it.y);x.scale(p,p);x.shadowBlur=reduced?0:24;x.shadowColor='#ffd85c';x.fillStyle='rgba(255,216,92,.18)';x.strokeStyle='#ffe889';x.lineWidth=3;x.beginPath();x.arc(0,0,22,0,Math.PI*2);x.fill();x.stroke();x.fillStyle='#fff3ad';x.beginPath();x.moveTo(0,-11);x.lineTo(9,-5);x.lineTo(7,7);x.lineTo(0,13);x.lineTo(-7,7);x.lineTo(-9,-5);x.closePath();x.fill();x.restore()}}
function player(){if(!reduced&&s.invuln>0&&s.shieldTime<=0&&Math.floor(performance.now()/70)%2===0)return;let a=s.player.x,b=s.player.y;x.save();if(s.shieldTime>0){x.strokeStyle='#ffe889';x.lineWidth=4;x.shadowBlur=reduced?0:22;x.shadowColor='#ffe06b';x.beginPath();x.arc(a,b,23,0,Math.PI*2);x.stroke()}x.shadowBlur=20;x.shadowColor='#57e7ff';x.fillStyle='#d8fbff';x.beginPath();x.arc(a,b,PR,0,Math.PI*2);x.fill();x.strokeStyle='#57e7ff';x.lineWidth=3;x.stroke();x.restore()}
function dashFx(){if(reduced||!s.dashFx)return;let f=s.dashFx,p=cl(f.age/f.duration,0,1),fade=1-p;x.save();x.strokeStyle=`rgba(87,231,255,${.85*fade})`;x.lineWidth=10*fade+2;x.beginPath();x.moveTo(f.fromX,f.fromY);x.lineTo(f.toX,f.toY);x.stroke();x.restore()}
function clearFx(){if(reduced||!s.clearFx)return;let t=cl((performance.now()-s.clearFx.startedAt)/(s.clearFx.duration*1000),0,1);if(t>=1){s.clearFx=null;return}x.save();x.globalAlpha=1-t;x.strokeStyle='#75eaff';x.lineWidth=4;for(let i=0;i<3;i++){let r=40+cl((t-i*.12)/(1-i*.12),0,1)*360;x.beginPath();x.arc(480,270,r,0,Math.PI*2);x.stroke()}x.restore()}
function drawH(h){let w=h.t<h.warning,a=h.t>=h.warning&&h.t<h.warning+h.active,p=cl(h.t/h.warning,0,1);x.save();x.lineWidth=2;x.strokeStyle=w?'rgba(255,101,120,.9)':'rgba(255,169,112,.98)';x.fillStyle=w?`rgba(255,83,105,${.15+.22*p})`:'rgba(255,67,78,.66)';if(h.type==='circle'){x.beginPath();x.arc(h.x,h.y,h.r,0,Math.PI*2);x.fill();x.stroke()}else if(h.type==='donut'){x.beginPath();x.arc(h.x,h.y,h.outer,0,Math.PI*2);x.arc(h.x,h.y,h.inner,0,Math.PI*2,true);x.fill('evenodd');x.stroke()}else if(h.type==='beam'){x.translate(480,270);x.rotate(h.angle);x.fillRect(-960,-h.width/2,1920,h.width);x.strokeRect(-960,-h.width/2,1920,h.width)}else{x.fillRect(h.x-h.width/2,18,h.width,450);x.fillRect(18,h.y-h.width/2,924,h.width)}x.restore()}
function parts(){if(reduced)return;for(let p of s.particles){x.globalAlpha=Math.max(0,p.life/p.max);x.fillStyle=p.color;x.fillRect(p.x-2,p.y-2,4,4)}x.globalAlpha=1}
function ui(){U.time.textContent=s.timeLeft.toFixed(1);U.phase.textContent=`PHASE ${s.phase}`;U.boss.style.width=`${Math.max(0,s.timeLeft/ROUND*100)}%`;U.hearts.textContent=('♥ '.repeat(s.hp)+'♡ '.repeat(5-s.hp)).trim();U.score.textContent=Math.floor(s.score).toLocaleString();U.combo.textContent=`x${s.combo}`;U.dash.textContent=s.dashCooldown<=0?'READY':`${s.dashCooldown.toFixed(1)}s`;U.shield.textContent=s.shieldTime>0?`${s.shieldTime.toFixed(1)}s`:'-';U.state.textContent=s.mode.toUpperCase();U.wins.textContent=rec.wins;U.bestScore.textContent=rec.bestScore.toLocaleString();U.bestTime.textContent=rec.bestTime.toFixed(1)}
function frame(t){try{let dt=Math.max(0,Math.min(.033,(t-last)/1000||0));last=t;update(dt);render();raf=requestAnimationFrame(frame)}catch(e){dbg.errors.push(String(e));console.error(e);cancelAnimationFrame(raf)}}function dir(code,on){if(code==='KeyW'||code==='ArrowUp')inp.up=on;if(code==='KeyS'||code==='ArrowDown')inp.down=on;if(code==='KeyA'||code==='ArrowLeft')inp.left=on;if(code==='KeyD'||code==='ArrowRight')inp.right=on}
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();dir(e.code,1);if(e.repeat)return;if(e.code==='Space')dash();else if(e.code==='KeyP')pause();else if(e.code==='KeyR'&&['success','fail'].includes(s.mode))start()});addEventListener('keyup',e=>dir(e.code,0));addEventListener('blur',()=>{if(s.mode==='playing'){blurPause=true;pause(true)}});addEventListener('focus',()=>{if(blurPause){blurPause=false;pause(false)}});addEventListener('resize',ui);U.startBtn.addEventListener('click',start);U.restartBtn.addEventListener('click',start);U.fxBtn.addEventListener('click',()=>{reduced=!reduced;document.body.classList.toggle('reduced-effects',reduced);U.fxBtn.setAttribute('aria-pressed',String(reduced));U.fxBtn.textContent=`파티클/흔들림 줄이기: ${reduced?'ON':'OFF'}`;if(reduced){s.particles.length=0;s.screenShake=0;s.dashFx=null;s.clearFx=null}});
function cl(v,a,b){return Math.max(a,Math.min(b,v))}function rnd(a,b){return a+Math.random()*(b-a)}window.__raidZeroDebug={getState:()=>JSON.parse(JSON.stringify(s)),getRecords:()=>({...rec}),getCounters:()=>({...dbg}),start,restart:start,pause:()=>pause(true),resume:()=>pause(false),dash,corruptSave:t=>localStorage.setItem(KEY,t),clearSave:()=>localStorage.removeItem(KEY),reloadRecords:()=>{rec=load();ui();return{...rec}},config:{ROUND_SECONDS:ROUND,ATTACK_INTERVAL_MS:INT,STORAGE_KEY:KEY,S_MIN_DODGES:S_DODGE,S_MIN_SCORE:S_SCORE,DASH_INVULN:DASH_I,SHIELD_INVULN:SHIELD_I}};reset();raf=requestAnimationFrame(frame)
})();